spring:
  application:
    name: shardingsphere-agent-master-test
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:demo.yaml
